name: App Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
        # Do not need to setup NodeJS since runner ubuntu-latest has it preinstalled but added this step as example
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with: 
          node-version: 18
      - name: Install Dependencies
        # This is the same as npm install but ci but uses dependency versions that are locked into the package-lock.json file. NPM feature to make sure using exact same versions used during development
        run: npm ci
      - name: Run tests
        run: npm test